### ISSUE TITLE
Keybindings not working on macOS

### ISSUE THREAD

**Issue by merchako** [taizod1024/vscode-boxdraw-extension#6]
I love the thought and design behind your extension. It would enable me to express so many ideas well in comments and in plaintext. I can tell you've designed your keybindings for Windows or Linux. I tried your extension on macOS, and VSCode+macOS really don't like them! 

I was able to enable / disable boxdraw mode with `ctrl + alt + m`, but I wasn't able to draw ruled line characters `ctrl + arrow key`. My guess is that these key bindings must interfere with some of macOS's keybindings. If you were able to offer an alternative keybindings, that would be very helpful to us. 

I love what you have done, and it would make me happy for more people to use it.

**Comment by taizod1024** [comment]
Thank you for trying out the extension!
I'll think of an alternative that works with macOS.

**Comment by taizod1024** [comment]
Added keybindings so that lines can be drawn with the alt key.

| function                                             | keyboard shortcuts                                      |
| ---------------------------------------------------- | ------------------------------------------------------- |
| draw ruled line characters                           | `ctrl + arrow key` or `alt + arrow key`                 |
| draw arrow characters                                | `ctrl + alt + arrow key`                                |
| clear characters                                     | `ctrl + shift + arrow key` or `alt + shift + arrow key` |
| switch the drawing mode (ruled line + arrow / block) | `ctrl + alt + b`                                        |
| move the cursor up and down                          | `up / down arrow key`                                   |
